# production builds on master branch
-
  branches:
    only:
      - master
  
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
    - ps: Install-Product node "0.10"
    - git clone -q https://github.com/Pyrax/node-pawn-scanner.git c:\samp\tools\scanner
  build_script:
    - cd c:\samp\bin && compile.bat
  after_build:
    - cd c:\samp\tools\scanner && node "bin\scan-dir.js" "c:\samp\src\gamemodes" && node "bin\scan-dir.js" "c:\samp\src\filterscripts"
  
  environment:
    samp_ftp_server: 178.33.168.68
    samp_ftp_user:
      secure: tVR2oHpGse5AUzlcZAvgAA==
    samp_ftp_password:
      secure: itEa/+YblFNt98JnaH71TA==
    web_ftp_server: ftp://upkkd09f439a.piranha.koding.io/
    web_ftp_user: piranha
    web_ftp_password:
      secure: itEa/+YblFNt98JnaH71TA==
  
  deploy_script: cd c:\samp\bin\appveyor && npm install ftp-deploy && node "deploy.js" && node "web-deploy.js"
  
# other branches are executed in the development environment
-
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
  build_script:
    - cd c:\samp\bin && compile.bat