# production builds on master branch
-
  branches:
    only:
      - master
  
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
    - ps: Install-Product node "0.10"
    - npm install -g ftp
    - git clone -q https://github.com/Pyrax/node-pawn-scanner.git c:\samp\tools\scanner
  build_script:
    - cd c:\samp\bin && compile.bat
  after_build:
    - cd c:\samp\tools\scanner && node "bin\scan-dir.js" "c:\samp\src\gamemodes" && node "bin\scan-dir.js" "c:\samp\src\filterscripts"
  
  environment:
    samp_ftp_server: 178.33.168.68
    samp_ftp_user:
      secure: tVR2oHpGse5AUzlcZAvgAA==
    samp_ftp_password:
      secure: itEa/+YblFNt98JnaH71TA==
    web_ftp_server: 0
    web_ftp_user: 0
    web_ftp_password: 0
  
  deploy_script: cd c:\samp\bin\appveyor && node "deploy.js"
  deploy: off
  
  #artifacts:
  #  - path: bin\server
  #    name: serverfiles
  #  - path: tools\scanner\web
  #    name: webfiles
  # deploy script to your server after it has been built
  #deploy:
  #  - provider: FTP
  #    server: 178.33.168.68
  #    username: 
  #      secure: tVR2oHpGse5AUzlcZAvgAA==
  #    password:
  #      secure: itEa/+YblFNt98JnaH71TA==
  #    folder:
  #    enable_ssl: false
  #    artifact: serverfiles
  #    
  #  - provider: FTP
  #    server:
  #    username:
  #    password:
  #    folder:
  #    enable_ssl: false
  #    artifact: webfiles

# other branches are executed in the development environment
-
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
  build_script:
    - cd c:\samp\bin && compile.bat