# production builds on master branch
-
  branches:
    only:
      - master
  
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
    - ps: Install-Product node "0.10"
    - git clone -q https://github.com/Pyrax/node-pawn-scanner.git c:\tools\scanner
  build_script:
    - cd c:\samp\bin && compile.bat
  after_build:
    - cd c:\tools\scanner && node "bin\scan-dir.js" "c:\samp\src\gamemodes" && node "bin\scan-dir.js" "c:\samp\src\filterscripts"
  
  artifacts:
    - path: 'c:\samp\bin\server'
      name: serverfiles
    - path: 'c:\tools\scanner\web'
      name: webfiles
  # deploy script to your server after it has been built
  deploy:
    - provider: FTP
      server:
      username:
      password:
      folder:
      enable_ssl: false
      artifact: serverfiles
      
    - provider: FTP
      server:
      username:
      password:
      folder:
      enable_ssl: false
      artifact: webfiles

# other branches are executed in the development environment
-
  version: 1.{build}
  
  # clone directory
  clone_folder: c:\samp
  
  # install (after repo cloning)
  install:
    - git submodule update -q --init --recursive
  build_script:
    - cd c:\samp\bin && compile.bat